word-congress-demo:
  non-reactive:
    nasa-api-schema: https
    nasa-api-hostname: images-api.nasa.gov
    nasa-api-search-endpoint: /search
    nasa-api-asset-endpoint: /asset
    nasa-api-captions-endpoint: /captions
    nasa-api-album-endpoint: /album
    api-key: ${API_KEY}

logging:
  level:
    'org.springframework.boot': OFF
    'org.springframework.data': OFF
    'org.springframework.web': OFF
    'org.mongodb': OFF
    'de.holisticon.reactive.Application': OFF

spring:
  data:
    mongodb:
      uri: mongodb://racoon:secr3t@localhost:27017/racoon-db?serverSelectionTimeoutMS=600000&connectTimeoutMS=600000&socketTimeoutMS=600000&waitQueueTimeoutMS=600000

